# Generated by Django 4.2.1 on 2023-05-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/genero'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/juegos'),
        ),
    ]
