# Generated by Django 4.2.2 on 2023-11-22 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_genero_foto_alter_juego_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.IntegerField(choices=[(1, 'Facil'), (2, 'Medio'), (3, 'Dificil')])),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_maximo', models.IntegerField()),
                ('repeticion_permitida', models.IntegerField()),
                ('actividad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='administracion.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Audio'), (2, 'Partitura')])),
                ('tiempo', models.IntegerField()),
                ('archivo', models.ImageField(blank=True, null=True, upload_to='media/recurso')),
            ],
        ),
        migrations.RemoveField(
            model_name='juego',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
        migrations.AddField(
            model_name='nivel',
            name='recursos',
            field=models.ManyToManyField(related_name='recursos', to='administracion.recurso'),
        ),
    ]
